import { lazy, type ComponentType, type LazyExoticComponent } from 'react';
import type { ModuleComponentProps } from '@/types';

// Each entry is a dynamic import, so Vite gives it its own chunk. Only the
// module the user actually opens (plus its own dependencies, e.g.
// libphonenumber-js for PhoneAnalyze or exifr for ExifPeek) is fetched, kept
// out of the initial panel bundle.
export const MODULE_COMPONENTS: Record<string, LazyExoticComponent<ComponentType<ModuleComponentProps>>> = {
  autofinder: lazy(() => import('@/components/modules/autofinder/AutoFinder')),
  bulkopen: lazy(() => import('@/components/modules/bulkopen/BulkOpen')),
  headergrade: lazy(() => import('@/components/modules/headergrade/HeaderGrade')),
  cookiejar: lazy(() => import('@/components/modules/cookiejar/CookieJar')),
  subfinder: lazy(() => import('@/components/modules/subfinder/SubFinder')),
  bucketspot: lazy(() => import('@/components/modules/bucketspot/BucketSpot')),
  encoderkit: lazy(() => import('@/components/modules/encoderkit/EncoderKit')),
  reconbuild: lazy(() => import('@/components/modules/reconbuild/ReconBuild')),
  shellgen: lazy(() => import('@/components/modules/shellgen/ShellGen')),
  payloadlib: lazy(() => import('@/components/modules/payloadlib/PayloadLib')),
  linuxcmds: lazy(() => import('@/components/modules/linuxcmds/LinuxCmds')),
  peasget: lazy(() => import('@/components/modules/peasget/PEASGet')),
  exifpeek: lazy(() => import('@/components/modules/exifpeek/ExifPeek')),
  linkgrab: lazy(() => import('@/components/modules/linkgrab/LinkGrab')),
  jslist: lazy(() => import('@/components/modules/jslist/JSList')),
  secretscan: lazy(() => import('@/components/modules/secretscan/SecretScan')),
  guidebook: lazy(() => import('@/components/modules/guidebook/GuideBook')),
  uploadtest: lazy(() => import('@/components/modules/uploadtest/UploadTest')),
  headerinject: lazy(() => import('@/components/modules/headerinject/HeaderInject')),
  uaswitch: lazy(() => import('@/components/modules/uaswitch/UASwitch')),
  refcontrol: lazy(() => import('@/components/modules/refcontrol/RefControl')),
  reqlogger: lazy(() => import('@/components/modules/reqlogger/ReqLogger')),
  sslinspect: lazy(() => import('@/components/modules/sslinspect/SSLInspect')),
  faviconhash: lazy(() => import('@/components/modules/faviconhash/FaviconHash')),
  ipgeo: lazy(() => import('@/components/modules/ipgeo/IPGeo')),
  shodanpeek: lazy(() => import('@/components/modules/shodanpeek/ShodanPeek')),
  clickjackcheck: lazy(() => import('@/components/modules/clickjackcheck/ClickjackCheck')),
  cspaudit: lazy(() => import('@/components/modules/cspaudit/CSPAudit')),
  corscheck: lazy(() => import('@/components/modules/corscheck/CORSCheck')),
  retirejs: lazy(() => import('@/components/modules/retirejs/RetireJS')),
  redirecttrace: lazy(() => import('@/components/modules/redirecttrace/RedirectTrace')),
  cvelookup: lazy(() => import('@/components/modules/cvelookup/CVELookup')),
  httpmethods: lazy(() => import('@/components/modules/httpmethods/HTTPMethods')),
  storagedump: lazy(() => import('@/components/modules/storagedump/StorageDump')),
  techstack: lazy(() => import('@/components/modules/techstack/TechStack')),
  wafdetect: lazy(() => import('@/components/modules/wafdetect/WAFDetect')),
  robotspeek: lazy(() => import('@/components/modules/robotspeek/RobotsPeek')),
  sitemapfind: lazy(() => import('@/components/modules/sitemapfind/SitemapFind')),
  wellknownscan: lazy(() => import('@/components/modules/wellknownscan/WellKnownScan')),
  panelhunt: lazy(() => import('@/components/modules/panelhunt/PanelHunt')),
  gitfinder: lazy(() => import('@/components/modules/gitfinder/GitFinder')),
  wayback: lazy(() => import('@/components/modules/wayback/Wayback')),
  contactgrab: lazy(() => import('@/components/modules/contactgrab/ContactGrab')),
  emailhunter: lazy(() => import('@/components/modules/emailhunter/EmailHunter')),
  emailanalyze: lazy(() => import('@/components/modules/emailanalyze/EmailAnalyze')),
  breachcheck: lazy(() => import('@/components/modules/breachcheck/BreachCheck')),
  phoneanalyze: lazy(() => import('@/components/modules/phoneanalyze/PhoneAnalyze')),
  googledork: lazy(() => import('@/components/modules/googledork/GoogleDork')),
  gitdork: lazy(() => import('@/components/modules/gitdork/GitDork')),
  fuzzbuild: lazy(() => import('@/components/modules/fuzzbuild/FuzzBuild')),
  wordlistpick: lazy(() => import('@/components/modules/wordlistpick/WordlistPick')),
  steggen: lazy(() => import('@/components/modules/steggen/StegGen')),
  blindxss: lazy(() => import('@/components/modules/blindxss/BlindXSS')),
  blindsqli: lazy(() => import('@/components/modules/blindsqli/BlindSQLi')),
  phpfilterchain: lazy(() => import('@/components/modules/phpfilterchain/PHPFilterChain')),
  formaudit: lazy(() => import('@/components/modules/formaudit/FormAudit')),
  hiddenfind: lazy(() => import('@/components/modules/hiddenfind/HiddenFind')),
  linkedcontent: lazy(() => import('@/components/modules/linkedcontent/LinkedContent')),
  targetsave: lazy(() => import('@/components/modules/targetsave/TargetSave')),
  exportall: lazy(() => import('@/components/modules/exportall/ExportAll')),
  copyascurl: lazy(() => import('@/components/modules/copyascurl/CopyAsCurl')),
  jsonview: lazy(() => import('@/components/modules/jsonview/JSONView')),
  takeovercheck: lazy(() => import('@/components/modules/takeovercheck/TakeoverCheck')),
  dnsrecords: lazy(() => import('@/components/modules/dnsrecords/DNSRecords')),
  dnsseccheck: lazy(() => import('@/components/modules/dnsseccheck/DNSSECCheck')),
  hostcluster: lazy(() => import('@/components/modules/hostcluster/HostCluster')),
  trackerscan: lazy(() => import('@/components/modules/trackerscan/TrackerScan')),
  whoislookup: lazy(() => import('@/components/modules/whoislookup/WhoisLookup')),
  reversewhois: lazy(() => import('@/components/modules/reversewhois/ReverseWhois')),
};
