import type { Browser } from 'wxt/browser';

export type CookieRecord = Browser.cookies.Cookie;

export function cookiePermissionPatterns(domain: string): string[] {
  const bare = domain.replace(/^\*\./, '');
  return [
    `https://${bare}/*`,
    `https://*.${bare}/*`,
    `http://${bare}/*`,
    `http://*.${bare}/*`,
  ];
}

export function cookieToNetscapeLine(cookie: CookieRecord): string {
  const domain = cookie.domain.startsWith('.') ? cookie.domain : cookie.domain;
  const includeSubdomains = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
  const expiry = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0;
  return [
    domain,
    includeSubdomains,
    cookie.path,
    cookie.secure ? 'TRUE' : 'FALSE',
    String(expiry),
    cookie.name,
    cookie.value,
  ].join('\t');
}

export function cookiesToNetscape(cookies: CookieRecord[]): string {
  const header = '# Netscape HTTP Cookie File\n# Generated by BugEye\n';
  return header + cookies.map(cookieToNetscapeLine).join('\n');
}

export function cookiesToHeader(cookies: CookieRecord[]): string {
  return cookies.map((c) => `${c.name}=${c.value}`).join('; ');
}

export interface ParsedImportCookie {
  domain: string;
  name: string;
  value: string;
  path: string;
  secure: boolean;
  httpOnly: boolean;
  sameSite?: string;
  expirationDate?: number;
}

export function parseNetscapeCookies(text: string): ParsedImportCookie[] {
  return text
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'))
    .map((line): ParsedImportCookie | null => {
      const parts = line.split('\t');
      if (parts.length < 7) return null;
      const [domain, , path, secure, expiry, name, value] = parts;
      return {
        domain: domain!,
        path: path || '/',
        secure: secure === 'TRUE',
        httpOnly: false,
        expirationDate: Number(expiry) > 0 ? Number(expiry) : undefined,
        name: name!,
        value: value ?? '',
      };
    })
    .filter((c): c is ParsedImportCookie => c !== null);
}

export function parseImportInput(text: string): ParsedImportCookie[] {
  const trimmed = text.trim();
  if (!trimmed) return [];
  if (trimmed.startsWith('[') || trimmed.startsWith('{')) {
    const json = JSON.parse(trimmed);
    const arr = Array.isArray(json) ? json : [json];
    return arr.map((c) => ({
      domain: c.domain,
      name: c.name,
      value: c.value,
      path: c.path ?? '/',
      secure: !!c.secure,
      httpOnly: !!c.httpOnly,
      sameSite: c.sameSite,
      expirationDate: c.expirationDate,
    }));
  }
  return parseNetscapeCookies(trimmed);
}

export function cookieSetUrl(cookie: ParsedImportCookie): string {
  const domain = cookie.domain.replace(/^\./, '');
  const scheme = cookie.secure ? 'https' : 'http';
  return `${scheme}://${domain}${cookie.path}`;
}

export function cookieRemoveUrl(cookie: CookieRecord): string {
  const domain = cookie.domain.replace(/^\./, '');
  const scheme = cookie.secure ? 'https' : 'http';
  return `${scheme}://${domain}${cookie.path}`;
}

export type CookieFindingSeverity = 'fail' | 'warn' | 'pass';

export interface CookieFinding {
  id: string;
  severity: CookieFindingSeverity;
  detail: string;
}

export function auditCookie(cookie: CookieRecord): CookieFinding[] {
  const findings: CookieFinding[] = [];
  const hostOnly = !cookie.domain.startsWith('.');
  const sameSite = cookie.sameSite ?? 'unspecified';

  if (cookie.name.startsWith('__Host-')) {
    const ok = cookie.secure && cookie.path === '/' && hostOnly;
    findings.push({
      id: 'host-prefix',
      severity: ok ? 'pass' : 'fail',
      detail: ok
        ? '__Host- prefix rules met (Secure, Path=/, host-only).'
        : `__Host- requires Secure, Path=/, and no Domain attribute. Got secure=${cookie.secure}, path=${cookie.path}, domain=${cookie.domain}.`,
    });
  } else if (cookie.name.startsWith('__Secure-')) {
    findings.push({
      id: 'secure-prefix',
      severity: cookie.secure ? 'pass' : 'fail',
      detail: cookie.secure
        ? '__Secure- prefix requires Secure: ok.'
        : '__Secure- cookies must be marked Secure.',
    });
  }

  if (sameSite === 'no_restriction') {
    findings.push({
      id: 'samesite-none',
      severity: cookie.secure ? 'warn' : 'fail',
      detail: cookie.secure
        ? 'SameSite=None (Chrome: no_restriction). Cross-site cookies; confirm this is intentional.'
        : 'SameSite=None without Secure is rejected by modern browsers.',
    });
  } else if (sameSite === 'unspecified') {
    findings.push({
      id: 'samesite-missing',
      severity: 'warn',
      detail: 'SameSite not set. Chrome defaults to Lax; older clients may treat this as None.',
    });
  } else {
    findings.push({
      id: 'samesite',
      severity: 'pass',
      detail: `SameSite=${sameSite}.`,
    });
  }

  if (!cookie.secure) {
    findings.push({
      id: 'secure',
      severity: 'fail',
      detail: 'Missing Secure - cookie may be sent over HTTP.',
    });
  }
  if (!cookie.httpOnly) {
    findings.push({
      id: 'httponly',
      severity: 'warn',
      detail: 'Missing HttpOnly - page JavaScript can read this cookie.',
    });
  }

  return findings;
}

export function cookieWorstSeverity(findings: CookieFinding[]): CookieFindingSeverity {
  if (findings.some((f) => f.severity === 'fail')) return 'fail';
  if (findings.some((f) => f.severity === 'warn')) return 'warn';
  return 'pass';
}
