import type { Browser } from 'wxt/browser';

export type CookieRecord = Browser.cookies.Cookie;

export function cookiePermissionPatterns(domain: string): string[] {
  const bare = domain.replace(/^\*\./, '');
  return [
    `https://${bare}/*`,
    `https://*.${bare}/*`,
    `http://${bare}/*`,
    `http://*.${bare}/*`,
  ];
}

export function cookieToNetscapeLine(cookie: CookieRecord): string {
  const domain = cookie.domain.startsWith('.') ? cookie.domain : cookie.domain;
  const includeSubdomains = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
  const expiry = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0;
  return [
    domain,
    includeSubdomains,
    cookie.path,
    cookie.secure ? 'TRUE' : 'FALSE',
    String(expiry),
    cookie.name,
    cookie.value,
  ].join('\t');
}

export function cookiesToNetscape(cookies: CookieRecord[]): string {
  const header = '# Netscape HTTP Cookie File\n# Generated by BugEye\n';
  return header + cookies.map(cookieToNetscapeLine).join('\n');
}

export function cookiesToHeader(cookies: CookieRecord[]): string {
  return cookies.map((c) => `${c.name}=${c.value}`).join('; ');
}

export interface ParsedImportCookie {
  domain: string;
  name: string;
  value: string;
  path: string;
  secure: boolean;
  httpOnly: boolean;
  sameSite?: string;
  expirationDate?: number;
}

export function parseNetscapeCookies(text: string): ParsedImportCookie[] {
  return text
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'))
    .map((line): ParsedImportCookie | null => {
      const parts = line.split('\t');
      if (parts.length < 7) return null;
      const [domain, , path, secure, expiry, name, value] = parts;
      return {
        domain: domain!,
        path: path || '/',
        secure: secure === 'TRUE',
        httpOnly: false,
        expirationDate: Number(expiry) > 0 ? Number(expiry) : undefined,
        name: name!,
        value: value ?? '',
      };
    })
    .filter((c): c is ParsedImportCookie => c !== null);
}

export function parseImportInput(text: string): ParsedImportCookie[] {
  const trimmed = text.trim();
  if (!trimmed) return [];
  if (trimmed.startsWith('[') || trimmed.startsWith('{')) {
    const json = JSON.parse(trimmed);
    const arr = Array.isArray(json) ? json : [json];
    return arr.map((c) => ({
      domain: c.domain,
      name: c.name,
      value: c.value,
      path: c.path ?? '/',
      secure: !!c.secure,
      httpOnly: !!c.httpOnly,
      sameSite: c.sameSite,
      expirationDate: c.expirationDate,
    }));
  }
  return parseNetscapeCookies(trimmed);
}

export function cookieSetUrl(cookie: ParsedImportCookie): string {
  const domain = cookie.domain.replace(/^\./, '');
  const scheme = cookie.secure ? 'https' : 'http';
  return `${scheme}://${domain}${cookie.path}`;
}
